const testimonialsData = [
  {
    id: 1,
    image: "/images/testimonials.jpg",
    name: "Małgorzata",
    date: "Mama Pacjenta",
    stars: 5,
    text: "Wizyta z dzieckiem odbyła się w spokojnej, miłej atmosferze. Pan doktor przejrzyście i zrozumiale wytłumaczył jak mamy postępować przy naszym problemie. Jesteśmy bardzo zadowoleni.",
  },
  {
    id: 2,
    image: "/images/testimonials.jpg",
    name: "Emilia",
    date: "Pacjentka",
    stars: 5,
    text: "Chylę czoła Panu doktorowi za holistyczne podejście, skrupulatność i empatię. Dzięki Panu doktorowi mimo różnych schorzeń człowiek nie traci wiary. Otrzymałam zadowalający efekt wizyty, wytłumaczenie problemu i dalsze postępowanie.",
  },
  {
    id: 3,
    image: "/images/testimonials.jpg",
    name: "Kamil",
    date: "Syn Pacjentki",
    stars: 5,
    text: "Bardzo serdecznie polecam Pana Dr. Michała Szczubkowskiego. Jest niezwykle profesjonalnym i empatycznym specjalistą. Moja mama była operowana przez Pana Doktora i od początku do końca była pod wspaniałą opieką. Pan Doktor dokładnie wytłumaczył cały proces leczenia. Dzięki niemu moja mama szybko wróciła do zdrowia.",
  },
  {
    id: 4,
    image: "/images/testimonials.jpg",
    name: "Stanisława",
    date: "Pacjentka",
    stars: 5,
    text: "Pan Doktor Michał jest przesympatyczny i bardzo profesjonalny. Dzięki jego pomocy problem został szybko i sprawnie rozwiązany. Bardzo żałuję, że obecnie jest tak niewielu wspaniałych lekarzy jak doktor. Polecam z całego serca!",
  },
  {
    id: 5,
    image: "/images/testimonials.jpg",
    name: "Krystian",
    date: "Pacjent",
    stars: 5,
    text: "Bardzo dobry lekarz i fantastyczny człowiek. Humor i empatia, chęć pomocy to wszystko dało się odczuć już przy pierwszej wizycie. Szybka diagnoza i leczenie przyniosły efekt w postaci całkowitego wyeliminowania problemu.",
  },
  {
    id: 6,
    image: "/images/testimonials.jpg",
    name: "Jarek",
    date: "Pacjent",
    stars: 5,
    text: "Polecam jako wysokiej klasy lekarza specjalistę a przede wszystkim Człowieka.",
  },
  {
    id: 7,
    image: "/images/testimonials.jpg",
    name: "Stanisław",
    date: "Pacjent",
    stars: 5,
    text: "Dr. Szczubkowski to chirurg o wyjątkowej wiedzy i umiejętnościach. Jego profesjonalizm i doświadczenie sprawiają, że jest jednym z najlepszych specjalistów w swojej dziedzinie.",
  },
  {
    id: 8,
    image: "/images/testimonials.jpg",
    name: "Natalia",
    date: "Pacjentka",
    stars: 5,
    text: "Pan Doktor Michał Szczubkowski to profesjonalista, rzeczowy oraz zaangażowany z indywidualnym pełnym troski podejściem do pacjenta.",
  },
];

export default testimonialsData;
